/*------------------------------------------------------------------------------*/
/*PROCEDURE TO ADD A RETURN TRIP*/
CREATE OR REPLACE 
PROCEDURE "ADD_RETURN_TRIP" (TID  NUMBER)
AS
	TRAIN_NO NUMBER;
	TRP_DATE DATE;
	ARRIVAL VARCHAR2(30);
	DEPARTURE VARCHAR2(30);
BEGIN
	SELECT TRAIN_ID,TRIP_DATE,STARTING,DESTINATION 
	INTO TRAIN_NO,TRP_DATE,ARRIVAL,DEPARTURE
	FROM TRIP 
	WHERE TRIP_ID=TID;

	INSERT INTO TRIP VALUES(TID+1,TRAIN_NO,TRP_DATE+2,DEPARTURE,ARRIVAL);
END;
/*------------------------------------------------------------------------------*/
